---

  - name: Remove unneeded packages (Debian)
    apt:
      name: [ "ppp,", "pppconfig", "pppoeconf", "cpp", "gcc", "g++", "libx11-data", "xauth", "libxmuu1", "libxcb1", "libx11-6", "libxext6", "linux-source" ]
      purge: yes
      state: absent

  - name: Clean up leftover dhcp leases
    shell: "rm -f /var/lib/dhcp/*"
    tags: ['skip_ansible_lint']

  - name: Clean up apt (Debian)
    shell: "{{ item }}"
    changed_when: false
    with_items:
      - apt-get -y autoremove --purge
      - apt-get -y clean
